[pytest]
DJANGO_SETTINGS_MODULE = lpd_project.settings
python_files = test_*.py *_test.py
pythonpath = .
addopts =
    --disable-warnings
    --maxfail=1
    --nomigrations
norecursedirs =
    venv
    .venv
    env
    .env
    lector
    Lib
    Scripts
    build
    dist
    *.egg*