# Generated by Django 5.2.6 on 2025-10-03 21:01

import plate_detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=plate_detector.models.analyzed_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('plate_detected', models.BooleanField(default=False)),
                ('detected_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
