# Generated by Django 5.2.6 on 2025-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_detector', '0004_imageanalysis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='ABC123', max_length=10),
            preserve_default=False,
        ),
    ]
