# Generated by Django 5.2.6 on 2025-11-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_detector', '0005_vehicle_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plate',
        ),
        migrations.AlterField(
            model_name='platedetection',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
