# Generated by Django 5.2.6 on 2025-11-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_detector', '0006_remove_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platedetection',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
